package com.example.paddleocrlib

import android.graphics.Bitmap

data class BaseResult (
    var countryCode: String? = "",
    var cardImage: Bitmap? = null,
    var cardProfile: Bitmap? = null,
    var isPassport:Boolean = false,
    var isAfricaCard:Boolean = false,
    var isZimbabwe :Boolean = false,
    var showDataCard :String = "",
    var cardProbability :String? = "",
    var name :String? = "",
    var surname:String? = "",
    var fullName:String? = "",
    var idCard:String? = "",
    var idNumber:String? = "",
    var passportNumber :String? = "",
    var validity:String? = "",
    var issued:String? = "",
    var licenseNumber:String? = "",
    var dateOfBirth :String? = "",
    var sex :String? = "",
    var bloodGroup :String? = "",
    var nationality :String? = "",
    var birthCountry :String? = "",
    var status :String = "",
    var secondaryIdentifier :String? = "",
    var primaryIdentifier :String? = "",
    var lastName :String? = "",
    var villageOfOrigin :String? = "",
    var placeOfBirth:String? = "",
    var dateOfIssue:String? = "",
    var dateOfExpiry:String? = "",
    var placeOfIssue:String? = "",
    var country:String? = "",
    var countryOfResidence:String? = "",
    var cardType :String? = "",
    var type:String? = "",
    var authority :String? = "",
    var mrzNumber:String? = "",
    var profession:String? = "",
    var rawLine:String? = "",
    var district:String? = "",
    var division:String? = "",
    var location:String? = "",
    var subLocation:String? = "",
    var identifier:String? = "",
    var cardBackSideImage: Bitmap? =null,
    var cardFrontSideImage: Bitmap? =null,
    var faceImage: Bitmap? =null,
    var signature: MutableList<Bitmap>? = arrayListOf(),
    var backCardData:String? = "",
    var frontCardData:String? = "",
    var frontCardProbability:String? = "",
    var backCardProbability:String? = "",
)
